stages:
  partial_obs:
    cmd: julia --project=. experiments/partial_obs.jl
    deps:
      - experiments/partial_obs.jl
      - src
    params:
      - partial_obs
    outs:
      - data/partial_obs/comparison.json
      - data/partial_obs/convergence.png
      - data/partial_obs/convergence.tikz
      - data/partial_obs/timing.png
      - data/partial_obs/timing.tikz
      - data/partial_obs/rmse.png
      - data/partial_obs/rmse.tikz
      - data/partial_obs/mnll.png
      - data/partial_obs/mnll.tikz
    metrics:
      - data/partial_obs/metrics.json:
          cache: false

  quadrature:
    cmd: julia --project=. experiments/quadrature.jl
    deps:
      - experiments/quadrature.jl
      - src
    params:
      - quadrature
    outs:
      - data/quadrature/comparison.json
      - data/quadrature/timing.png
      - data/quadrature/timing.tikz
      - data/quadrature/timelimit.png
      - data/quadrature/timelimit.tikz
      - data/quadrature/integral_error.png
      - data/quadrature/integral_error.tikz
      - data/quadrature/rmse.png
      - data/quadrature/rmse.tikz
    metrics:
      - data/quadrature/metrics.json:
          cache: false
